name: fast_csv
version: 0.2.10
description: Classic CSV parsers suitable for most use cases. Pretty fast parsing. With experimental event-based streaming parsing.
repository: https://github.com/mezoni/csv_parser
environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  lints: '>=1.0.0 <3.0.0'
  test: ^1.20.1
